application: webkameleon-developer-ae
version: 1
runtime: php55
api_version: 1

handlers:

- url: /media
  static_dir: media

- url: /check
  script: check.php
  login: admin

- url: /status
  script: status.php
  login: admin

- url: /.*
  script: index.php
  login: admin

